modLoader = "javafml"
loaderVersion="[36,)"
license="http://tslat.net/Hosting/Tslat-AoA/pages/license.html"
issueTrackerURL="https://github.com/Tslat/Advent-Of-Ascension/issues"
# Mod info
[[mods]]
modId="aoa3" # Mod ID
version="1.16.5-3.6.11"# Mod version
displayName="Advent of Ascension"
updateJSONURL="https://gist.github.com/Tslat/e7afe2448fe39a695acd45764824b762/raw/"
displayURL="https://adventofascension.gamepedia.com/Advent_of_Ascension_Wiki"
logoFile="logo.png"
credits="http://tslat.net/Hosting/Tslat-AoA/aoa_credits.txt"
authors="Tslat - Code | Ursun, NeoVolt, Keletosans - Visual Assets | Bleuhatt - Structures"
description='''
Nevermine the Eternal Isles, this is Advent of Ascension!
'''

[[dependencies.aoa3]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aoa3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

