modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved unless stated otherwise. Distrubtion permssion is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
# MekFix
modId = "mekfix" # Mod ID
version = "1.0.1-build.2+mc1.18.2"# Mod version
displayName = "MekFix"
description ='''
Fixes Mekanism XP dupe bug for 1.18.2

what can i say
'''