class BinaryByte:

  def __add__(self, other: "BinaryByte") -> "BinaryByte": ...

  def __sub__(self, other: "BinaryByte") -> "BinaryByte": ...

  def __mul__(self, other: "BinaryByte") -> "BinaryByte": ...

  def __truediv__(self, other: "BinaryByte") -> "BinaryByte": ...

  def toInteger(self) -> "BinaryInteger": ...

  def toFloat(self) -> "BinaryFloat": ...

  def toDouble(self) -> "BinaryDouble": ...

  def __str__(self): ...


class BinaryInteger:

  def toFloat(self) -> "BinaryFloat": ...

  def toDouble(self) -> "BinaryDouble": ...

  def __str__(self): ...


class BinaryFloat:

  def toInteger(self) -> BinaryInteger: ...

  def toDouble(self) -> "BinaryDouble": ...

  def __str__(self): ...


class BinaryDouble:

  def __str__(self): ...


class BinaryBoolean:

  def __str__(self): ...


class BinaryChar: ...
